<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property decimal $price
 * @property Doctrine_Collection $Photos
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method decimal             getPrice()  Returns the current record's "price" value
 * @method Doctrine_Collection getPhotos() Returns the current record's "Photos" collection
 * @method Product             setName()   Sets the current record's "name" value
 * @method Product             setPrice()  Sets the current record's "price" value
 * @method Product             setPhotos() Sets the current record's "Photos" collection
 * 
 * @package    intranet-cctb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductPhoto as Photos', array(
             'local' => 'id',
             'foreign' => 'product_id'));
    }
}