<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Fonction', 'doctrine');

/**
 * BaseFonction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property Doctrine_Collection $ContactPro
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getIntitule()   Returns the current record's "intitule" value
 * @method Doctrine_Collection getContactPro() Returns the current record's "ContactPro" collection
 * @method Fonction            setId()         Sets the current record's "id" value
 * @method Fonction            setIntitule()   Sets the current record's "intitule" value
 * @method Fonction            setContactPro() Sets the current record's "ContactPro" collection
 * 
 * @package    intranet-cctb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFonction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fonction');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('intitule', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ContactPro', array(
             'local' => 'id',
             'foreign' => 'fonction_id'));
    }
}