<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Region', 'doctrine');

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property Doctrine_Collection $Departement
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNom()         Returns the current record's "nom" value
 * @method Doctrine_Collection getDepartement() Returns the current record's "Departement" collection
 * @method Region              setId()          Sets the current record's "id" value
 * @method Region              setNom()         Sets the current record's "nom" value
 * @method Region              setDepartement() Sets the current record's "Departement" collection
 * 
 * @package    intranet-cctb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('nom', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Departement', array(
             'local' => 'id',
             'foreign' => 'region_id'));
    }
}