<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Module', 'doctrine');

/**
 * BaseModule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property Doctrine_Collection $Action
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getNom()    Returns the current record's "nom" value
 * @method Doctrine_Collection getAction() Returns the current record's "Action" collection
 * @method Module              setId()     Sets the current record's "id" value
 * @method Module              setNom()    Sets the current record's "nom" value
 * @method Module              setAction() Sets the current record's "Action" collection
 * 
 * @package    intranet-cctb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseModule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('module');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('nom', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Action', array(
             'local' => 'id',
             'foreign' => 'module_id'));
    }
}