<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ContactPro', 'doctrine');

/**
 * BaseContactPro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $personne_id
 * @property integer $groupe_id
 * @property integer $fonction_id
 * @property Personne $Personne
 * @property Groupe $Groupe
 * @property Fonction $Fonction
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method integer    getPersonneId()  Returns the current record's "personne_id" value
 * @method integer    getGroupeId()    Returns the current record's "groupe_id" value
 * @method integer    getFonctionId()  Returns the current record's "fonction_id" value
 * @method Personne   getPersonne()    Returns the current record's "Personne" value
 * @method Groupe     getGroupe()      Returns the current record's "Groupe" value
 * @method Fonction   getFonction()    Returns the current record's "Fonction" value
 * @method ContactPro setId()          Sets the current record's "id" value
 * @method ContactPro setPersonneId()  Sets the current record's "personne_id" value
 * @method ContactPro setGroupeId()    Sets the current record's "groupe_id" value
 * @method ContactPro setFonctionId()  Sets the current record's "fonction_id" value
 * @method ContactPro setPersonne()    Sets the current record's "Personne" value
 * @method ContactPro setGroupe()      Sets the current record's "Groupe" value
 * @method ContactPro setFonction()    Sets the current record's "Fonction" value
 * 
 * @package    intranet-cctb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseContactPro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactPro');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('personne_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('groupe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('fonction_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Personne', array(
             'local' => 'personne_id',
             'foreign' => 'id'));

        $this->hasOne('Groupe', array(
             'local' => 'groupe_id',
             'foreign' => 'id'));

        $this->hasOne('Fonction', array(
             'local' => 'fonction_id',
             'foreign' => 'id'));
    }
}