<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ville', 'doctrine');

/**
 * BaseVille
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $departement_id
 * @property string $nom
 * @property Departement $Departement
 * @property Doctrine_Collection $Adresse
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getDepartementId()  Returns the current record's "departement_id" value
 * @method string              getNom()            Returns the current record's "nom" value
 * @method Departement         getDepartement()    Returns the current record's "Departement" value
 * @method Doctrine_Collection getAdresse()        Returns the current record's "Adresse" collection
 * @method Ville               setId()             Sets the current record's "id" value
 * @method Ville               setDepartementId()  Sets the current record's "departement_id" value
 * @method Ville               setNom()            Sets the current record's "nom" value
 * @method Ville               setDepartement()    Sets the current record's "Departement" value
 * @method Ville               setAdresse()        Sets the current record's "Adresse" collection
 * 
 * @package    intranet-cctb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseVille extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ville');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('departement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('nom', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Departement', array(
             'local' => 'departement_id',
             'foreign' => 'region_id'));

        $this->hasMany('Adresse', array(
             'local' => 'id',
             'foreign' => 'ville_id'));
    }
}