<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Action', 'doctrine');

/**
 * BaseAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $intitule
 * @property integer $module_id
 * @property Module $Module
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getIntitule()  Returns the current record's "intitule" value
 * @method integer getModuleId()  Returns the current record's "module_id" value
 * @method Module  getModule()    Returns the current record's "Module" value
 * @method Action  setId()        Sets the current record's "id" value
 * @method Action  setIntitule()  Sets the current record's "intitule" value
 * @method Action  setModuleId()  Sets the current record's "module_id" value
 * @method Action  setModule()    Sets the current record's "Module" value
 * 
 * @package    intranet-cctb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('action');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('intitule', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('module_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Module', array(
             'local' => 'module_id',
             'foreign' => 'id'));
    }
}