<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/12/14 16:32:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=intranet-cctb',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
